import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/UserProvider";
import { getUser } from "@/utils/getUser";
import SideMenu from "@/components/shared/SideMenu";
import { Poppins } from "next/font/google";
import ReduxProvider from "@/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Luxera Admin",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await getUser();

  return (
    <html lang="en">
      <body className={`${poppins.className} bg-dark-gray min-h-screen`}>
        <ReduxProvider>
          <UserProvider userData={userData?.user}>
            <div className="w-full flex h-full">
              <SideMenu />
              <main className="w-full">{children}</main>
            </div>
          </UserProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
