import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Luxera Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 min-h-screen px-4">{children}</body>
    </html>
  );
}
