import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/UserProvider";
import { getUser } from "@/utils/getUser";

export const metadata: Metadata = {
  title: "Luxera Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await getUser();

  return (
    <html lang="en">
      <body className="bg-gray-900 min-h-screen px-4">
        <UserProvider userData={userData?.user}>{children}</UserProvider>
      </body>
    </html>
  );
}
